import { RootContext } from '../types'

/** The attribution line used in the header comment of every generated file. */
export function generatedBy(root: RootContext): string {
	return `Generated by ${root.generatorClass}${root.hideGenerationTimestamp ? '' : ` on ${root.generatedDate}`}`
}
